USE [academycoding2]
GO

/****** Object:  Table [dbo].[CALLED]    Script Date: 11/06/2021 17:38:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CALLED](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Finished] [char](1) NOT NULL,
	[Descripition] [varchar](300) NOT NULL,
	[PriorityId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CALLED]  WITH CHECK ADD  CONSTRAINT [FK_Priority_id] FOREIGN KEY([PriorityId])
REFERENCES [dbo].[PRIORITY] ([Id])
GO

ALTER TABLE [dbo].[CALLED] CHECK CONSTRAINT [FK_Priority_id]
GO

